- name: add /etc/hosts
  copy: src=hosts dest=/etc/ mode=0644
  become: yes
  
- name: install python
  become: yes
  yum:
    name: python
    state: present
 
- name: install pip
  become: yes
  command: easy_install pip
 
- name: install ansible
  become: yes
  yum:
    name: ansible
    state: present
